apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
  - name: busybox-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo 'Hello from Busybox'; sleep 10; done"]
  - name: alpine-container
    image: alpine
    command: ["/bin/sh", "-c", "while true; do echo 'Hello from Alpine'; sleep 10; done"]