apiVersion: v1
kind: Pod
metadata:
  name: box0
spec:
  containers:
  - name: box0-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - "[ -f /tmp/debug ]"
      initialDelaySeconds: 10
      periodSeconds: 5
  initContainers:
  - name: init-debug
    image: busybox
    command: ["sh", "-c", "sleep 30; touch /tmp/debug; sleep 30; rm /tmp/debug"]
