apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.8-apache
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /readme.html
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5