apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  - name: busybox-container
    image: busybox
    command: ["wget", "-O", "/work-dir/index.html", "http://neverssl.com/online"]
    volumeMounts:
    - name: html-volume
      mountPath: /work-dir
  volumes:
  - name: html-volume
    emptyDir: {}
