# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-pod
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     livenessProbe:
#       exec:
#         command:
#         - ls
#       initialDelaySeconds: 5
#       periodSeconds: 5

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx-pod
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     livenessProbe:
#       exec:
#         command:
#         - ls
#       initialDelaySeconds: 0
#       periodSeconds: 5

# 

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80