apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume-secrets
spec:
  containers:
  - name: my-container
    image: busybox
    command: ["/bin/sh", "-c", "cat /mnt/secrets/username; cat /mnt/secrets/password"]
    volumeMounts:
    - name: secret-volume
      mountPath: /mnt/secrets
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret