apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcm5hbWU=  # Base64 encoded string of your username
  password: cGFzc3dvcmQ=  # Base64 encoded string of your password
